### ISSUE TITLE
ray_trace renders bitmaps upside-down

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/bicgl#1]
See thread http://www.bic.mni.mcgill.ca/pipermail/minc-users/2015-September/004156.html

**Comment by gdevenyi** [comment]
@rdvincent Did you get a chance to look at this yet?

**Comment by rdvincent** [comment]
It was fixed a while ago: https://github.com/BIC-MNI/bicpl/commit/f0aba22b995c97db983bdf1492b0649207b8c341

**Comment by gdevenyi** [comment]
Cheers!
